### ISSUE TITLE
User can view a task list.

### ISSUE THREAD

**Issue by JohnLeeJH** [JohnLeeJH/Daily-task-manager-app#3]
# Motivation
User can view a task list after they have been added.

## Implements
- [x] Create design for frame task manager feature
- [x] Design task input area
- [x] Arrange buttons and icons inline with task messages

Screen Capture:
![image](https://cloud.githubusercontent.com/assets/26069024/25874222/67766b46-34c6-11e7-8439-b846d81fe8be.png)
